name: Aggiorna Classifica Volley

on:
  schedule:
    # Ore UTC: 7, 12, 18 (che sono 8, 13, 19 in Italia Inverno)
    - cron: '0 7,12,18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installa Chrome Browser
        uses: browser-actions/setup-chrome@v1

      - name: Installa Dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Esegui lo Script
        run: python main.py

      - name: Salva e Pubblica
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Aggiornamento automatico classifica"
          file_pattern: "index.html"
